# Default values for core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  repo:         ""
  tag:          ""
  pullPolicy:   "Always"
  javaOpts:     "-Xmx4500m"
  imageName:    "pluto/psysjo-core17"



service:
  app:
    type: ClusterIP
    port: 7070


istio:
  enabled: true
  annotations: {}

resources:
  limits:
    cpu: 3000m
    memory: 5000Mi
  requests:
    cpu: 100m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
