apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ include "psysjo-core17.shortname" . }}"
  labels:
{{ include "psysjo-core17.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "psysjo-core17.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}